### ISSUE TITLE
Systematic OOM on Card Slider

### ISSUE THREAD

**Issue by anthony-skr** [Ramotion/showroom#23]
Tested with Galaxy S7. It happens after 5-6 slides.

> 11-21 14:34:02.862 2984-3724/com.ramotion.showroom E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                                     Process: com.ramotion.showroom, PID: 2984
                                                                     java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.OutOfMemoryError: Failed to allocate a 11760012 byte allocation with 11350800 free bytes and 10MB until OOM
                                                                         at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                         at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                         at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:856)
                                                                         at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:675)
                                                                         at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:703)
                                                                         at com.ramotion.showroom.examples.cardslider.utils.DecodeBitmapTask.doInBackground(DecodeBitmapTask.java:69)
                                                                         at com.ramotion.showroom.examples.cardslider.utils.DecodeBitmapTask.doInBackground(DecodeBitmapTask.java:19)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                         at java.lang.Thread.run(Thread.java:818)

**Comment by anthony-skr** [comment]
Wrong repo... sorry.
